export interface FormType {
  id: string;
  code: string;
  title: string;
  subtitle: string;
  category: string;
  requiresInspection: boolean;
  documentRequirements: DocumentRequirement[];
  estimatedTime: string; // e.g., "30-45 minutes"
  fees: string;
}

export interface DocumentRequirement {
  id: string;
  name: string;
  description: string;
  mandatory: boolean;
  format: string[]; // e.g., ['PDF', 'JPG']
  maxSize: string; // e.g., '5MB'
}

export const FORM_CATEGORIES = [
  {
    id: 'drug-sale',
    name: 'Drug Sale Licenses',
    description: 'Licenses for retail sale of drugs and medicines',
    icon: '💊',
  },
  {
    id: 'drug-manufacturing',
    name: 'Drug Manufacturing',
    description: 'Manufacturing licenses for pharmaceutical companies',
    icon: '🏭',
  },
  {
    id: 'blood-banking',
    name: 'Blood Banking & Products',
    description: 'Blood banks and blood product manufacturing',
    icon: '🩸',
  },
  {
    id: 'cosmetics',
    name: 'Cosmetics',
    description: 'Cosmetics manufacturing licenses',
    icon: '💄',
  },
  {
    id: 'testing',
    name: 'Testing & Analysis',
    description: 'Laboratory testing and analysis services',
    icon: '🔬',
  },
  {
    id: 'new-drugs',
    name: 'New Drugs & Clinical Trials',
    description: 'New drug approvals and clinical trial permissions',
    icon: '🧪',
  },
  {
    id: 'medical-institution',
    name: 'Medical Institution Recognition',
    description: 'Recognition for medical institutions and hospitals',
    icon: '🏥',
  },
];

export const ALL_FORMS: FormType[] = [
  // Drug Sale Licenses (4 forms)
  {
    id: 'form-19',
    code: '19',
    title: 'Form 19 - Drug Sale License (General)',
    subtitle: 'Pharmacy/Medical Store',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '30-45 minutes',
    fees: '₹5,000',
    documentRequirements: [
      {
        id: 'pharmacy-registration',
        name: 'Pharmacy Registration Certificate',
        description: 'Valid registration certificate from Pharmacy Council',
        mandatory: true,
        format: ['PDF', 'JPG', 'PNG'],
        maxSize: '5MB',
      },
      {
        id: 'premises-proof',
        name: 'Premises Ownership/Lease Proof',
        description: 'Property documents or lease agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'floor-plan',
        name: 'Floor Plan/Layout',
        description: 'Detailed floor plan of the premises',
        mandatory: true,
        format: ['PDF', 'JPG', 'PNG'],
        maxSize: '5MB',
      },
      {
        id: 'pharmacist-qualification',
        name: 'Pharmacist Qualification Certificate',
        description: 'Educational qualification certificates',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'id-proof',
        name: 'Identity Proof',
        description: 'Aadhaar/PAN/Passport of applicant',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '2MB',
      },
    ],
  },
  {
    id: 'form-19a',
    code: '19A',
    title: 'Form 19A - Restricted Drug Sale License',
    subtitle: 'Drug Dealer (No Pharmacist)',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '25-35 minutes',
    fees: '₹3,000',
    documentRequirements: [
      {
        id: 'business-registration',
        name: 'Business Registration Certificate',
        description: 'Shop Act or GST registration certificate',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'premises-proof',
        name: 'Premises Ownership/Lease Proof',
        description: 'Property documents or lease agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'id-proof',
        name: 'Identity Proof',
        description: 'Aadhaar/PAN/Passport of applicant',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '2MB',
      },
      {
        id: 'drug-list',
        name: 'List of Drugs to be Sold',
        description: 'Detailed list of restricted drugs',
        mandatory: true,
        format: ['PDF', 'XLSX'],
        maxSize: '2MB',
      },
    ],
  },
  {
    id: 'form-19b',
    code: '19B',
    title: 'Form 19B - Homoeopathic Medicine Sale',
    subtitle: 'Homoeopathic Shop',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '20-30 minutes',
    fees: '₹2,500',
    documentRequirements: [
      {
        id: 'homoeopathy-qualification',
        name: 'Homoeopathy Qualification Certificate',
        description: 'Valid degree/diploma in Homoeopathy',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'premises-proof',
        name: 'Premises Ownership/Lease Proof',
        description: 'Property documents or lease agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'floor-plan',
        name: 'Floor Plan/Layout',
        description: 'Layout of the shop',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '5MB',
      },
      {
        id: 'id-proof',
        name: 'Identity Proof',
        description: 'Aadhaar/PAN of applicant',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '2MB',
      },
    ],
  },
  {
    id: 'form-19c',
    code: '19C',
    title: 'Form 19C - Schedule X Drug Sale',
    subtitle: 'Pharmacy/Medical Store',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '35-50 minutes',
    fees: '₹7,500',
    documentRequirements: [
      {
        id: 'form-19-license',
        name: 'Existing Form 19 License',
        description: 'Valid Form 19 drug sale license',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'pharmacist-qualification',
        name: 'Pharmacist Qualification',
        description: 'B.Pharm or equivalent qualification',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'storage-facility',
        name: 'Special Storage Facility Proof',
        description: 'Documentation of secure storage for Schedule X drugs',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '10MB',
      },
      {
        id: 'record-system',
        name: 'Record Keeping System',
        description: 'Details of record maintenance system',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-20',
    code: '20',
    title: 'Form 20 - General Drug Sale Licence (Retail)',
    subtitle: 'Retail Drug Sale',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '35-50 minutes',
    fees: '₹6,000',
    documentRequirements: [
      {
        id: 'premises-proof',
        name: 'Premises Ownership/Lease Proof',
        description: 'Proof of premises ownership or lease agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'premises-layout',
        name: 'Premises Layout Plan',
        description: 'Layout showing retail area and storage facilities',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '10MB',
      },
      {
        id: 'pharmacist-certificate',
        name: 'Pharmacist Registration Certificate',
        description: 'Qualified pharmacist registration and qualification certificates',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'affidavit-supporting-docs',
        name: 'Affidavit & Supporting Documents',
        description: 'Affidavit and supporting compliance documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-21',
    code: '21',
    title: 'Form 21 - General Drug Sale Licence (Wholesale)',
    subtitle: 'Wholesale Drug Sale',
    category: 'drug-sale',
    requiresInspection: true,
    estimatedTime: '35-50 minutes',
    fees: '₹6,000',
    documentRequirements: [
      {
        id: 'premises-proof',
        name: 'Premises Ownership/Lease Proof',
        description: 'Proof of premises ownership or lease agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'premises-layout',
        name: 'Premises Layout Plan',
        description: 'Layout showing wholesale storage and handling areas',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '10MB',
      },
      {
        id: 'qualified-person-certificate',
        name: 'Qualified Person Certificate',
        description: 'Qualification and registration certificates of responsible person',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'affidavit-supporting-docs',
        name: 'Affidavit & Supporting Documents',
        description: 'Affidavit and supporting compliance documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  // Drug Manufacturing (11 forms)
  {
    id: 'form-24',
    code: '24',
    title: 'Form 24 - Drug Manufacturing (General)',
    subtitle: 'Pharma Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '60-90 minutes',
    fees: '₹50,000',
    documentRequirements: [
      {
        id: 'company-registration',
        name: 'Company Registration Certificate',
        description: 'ROC registration or partnership deed',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'factory-license',
        name: 'Factory License',
        description: 'Valid factory license from state authorities',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'gmp-certificate',
        name: 'GMP Certificate',
        description: 'Good Manufacturing Practice certificate',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'technical-staff',
        name: 'Technical Staff Qualifications',
        description: 'Qualifications of pharmacists and technical staff',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'plant-layout',
        name: 'Plant Layout and Equipment List',
        description: 'Detailed layout and machinery list',
        mandatory: true,
        format: ['PDF'],
        maxSize: '20MB',
      },
      {
        id: 'product-list',
        name: 'List of Products',
        description: 'Products proposed to be manufactured',
        mandatory: true,
        format: ['PDF', 'XLSX'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-24a',
    code: '24A',
    title: 'Form 24A - Loan Manufacturing Licence',
    subtitle: 'Loan Licensee (Borrowing Premises)',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '45-60 minutes',
    fees: '₹30,000',
    documentRequirements: [
      {
        id: 'manufacturing-concern-licence',
        name: 'Manufacturing Concern Existing Licence',
        description: 'Valid manufacturing licence of the firm whose premises are being borrowed',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'manufacturing-agreement',
        name: 'Manufacturing Agreement Letter',
        description: 'Signed agreement between loan licensee and manufacturing concern',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'consent-letter',
        name: 'Consent Letter from Manufacturing Concern',
        description: 'Explicit consent from the manufacturing concern for loan arrangement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'gmp-certificate',
        name: 'GMP Certificate',
        description: 'Good Manufacturing Practice certificate',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'labels-carton',
        name: 'Labels & Carton Specimens',
        description: 'Product labels and carton specimens showing loan licensee name',
        mandatory: true,
        format: ['PDF', 'JPG', 'PNG'],
        maxSize: '10MB',
      },
      {
        id: 'expert-staff-qualifications',
        name: 'Expert Staff Qualifications',
        description: 'Educational and professional qualifications of expert staff',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-24b',
    code: '24B',
    title: 'Form 24B - Drug Repacking',
    subtitle: 'Drug Repacker',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '40-55 minutes',
    fees: '₹25,000',
    documentRequirements: [
      {
        id: 'repacking-facility',
        name: 'Repacking Facility Details',
        description: 'Details of repacking facility and equipment',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'source-authorization',
        name: 'Source Authorization',
        description: 'Authorization from original manufacturer',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'quality-control',
        name: 'Quality Control Setup',
        description: 'Quality control and testing facilities',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'pharmacist-details',
        name: 'Pharmacist Qualification',
        description: 'Qualification of supervising pharmacist',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-24c',
    code: '24C',
    title: 'Form 24C - Homoeopathic Manufacturing',
    subtitle: 'Homoeopathic Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '50-70 minutes',
    fees: '₹35,000',
    documentRequirements: [
      {
        id: 'homoeopathy-qualification',
        name: 'Homoeopathy Expert Qualification',
        description: 'Degree in Homoeopathic Medicine',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'manufacturing-setup',
        name: 'Manufacturing Setup Details',
        description: 'Complete details of manufacturing facility',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'source-materials',
        name: 'Source Materials Certificate',
        description: 'Certificates for homoeopathic mother tinctures',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'product-list',
        name: 'Product List',
        description: 'List of homoeopathic medicines to be manufactured',
        mandatory: true,
        format: ['PDF', 'XLSX'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-24f',
    code: '24F',
    title: 'Form 24F - Schedule X Manufacturing',
    subtitle: 'Pharma Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '60-80 minutes',
    fees: '₹75,000',
    documentRequirements: [
      {
        id: 'form-24-license',
        name: 'Existing Form 24 License',
        description: 'Valid general manufacturing license',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'special-storage',
        name: 'Special Storage Facilities',
        description: 'Secured storage and handling facilities',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '15MB',
      },
      {
        id: 'security-measures',
        name: 'Security Measures Documentation',
        description: 'Security protocols for Schedule X drugs',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'qualified-personnel',
        name: 'Qualified Personnel Details',
        description: 'Details of qualified supervisory staff',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-27',
    code: '27',
    title: 'Form 27 - Schedule C & C(1) Manufacturing',
    subtitle: 'Medical Institution/Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '70-90 minutes',
    fees: '₹60,000',
    documentRequirements: [
      {
        id: 'institution-registration',
        name: 'Institution Registration',
        description: 'Registration with medical authorities',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'specialized-equipment',
        name: 'Specialized Equipment Details',
        description: 'Details of equipment for biological manufacturing',
        mandatory: true,
        format: ['PDF'],
        maxSize: '20MB',
      },
      {
        id: 'technical-expertise',
        name: 'Technical Expertise Certificates',
        description: 'Qualifications of technical personnel',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'biosafety-certification',
        name: 'Biosafety Certification',
        description: 'Biosafety level certification',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-27a',
    code: '27A',
    title: 'Form 27A - Loan License Schedule C & C(1)',
    subtitle: 'Medical Institution/Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '50-65 minutes',
    fees: '₹40,000',
    documentRequirements: [
      {
        id: 'principal-license',
        name: 'Principal License Copy',
        description: 'Form 27 license of principal manufacturer',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'loan-agreement',
        name: 'Loan Agreement',
        description: 'Signed loan manufacturing agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'technical-collaboration',
        name: 'Technical Collaboration Details',
        description: 'Details of technical collaboration',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-27b',
    code: '27B',
    title: 'Form 27B - Schedule C, C(1) & X Manufacturing',
    subtitle: 'Medical Institution/Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '80-100 minutes',
    fees: '₹85,000',
    documentRequirements: [
      {
        id: 'form-27-license',
        name: 'Existing Form 27 License',
        description: 'Valid Form 27 license',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'enhanced-security',
        name: 'Enhanced Security Measures',
        description: 'Additional security for Schedule X substances',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'specialized-training',
        name: 'Staff Training Certificates',
        description: 'Specialized training for handling controlled substances',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-27d',
    code: '27D',
    title: 'Form 27D - Large Volume Parenterals/Sera/Vaccines',
    subtitle: 'Pharma Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '90-120 minutes',
    fees: '₹1,00,000',
    documentRequirements: [
      {
        id: 'cleanroom-certification',
        name: 'Cleanroom Certification',
        description: 'ISO certified cleanroom facilities',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'sterilization-validation',
        name: 'Sterilization Validation',
        description: 'Validation reports for sterilization processes',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'quality-assurance',
        name: 'Quality Assurance System',
        description: 'Comprehensive QA/QC documentation',
        mandatory: true,
        format: ['PDF'],
        maxSize: '20MB',
      },
      {
        id: 'expert-personnel',
        name: 'Expert Personnel Qualifications',
        description: 'Highly qualified technical personnel details',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-27da',
    code: '27DA',
    title: 'Form 27DA - Loan License LVP/Sera/Vaccines',
    subtitle: 'Pharma Manufacturer',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '70-90 minutes',
    fees: '₹75,000',
    documentRequirements: [
      {
        id: 'principal-form-27d',
        name: 'Principal Form 27D License',
        description: 'Valid Form 27D license of principal',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'loan-agreement',
        name: 'Loan Manufacturing Agreement',
        description: 'Detailed loan agreement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'technical-transfer',
        name: 'Technology Transfer Documentation',
        description: 'Complete technology transfer documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
    ],
  },
  {
    id: 'form-30',
    code: '30',
    title: 'Form 30 - Manufacturing for Testing/Analysis',
    subtitle: 'Research Lab/Testing Facility',
    category: 'drug-manufacturing',
    requiresInspection: true,
    estimatedTime: '40-55 minutes',
    fees: '₹20,000',
    documentRequirements: [
      {
        id: 'laboratory-details',
        name: 'Laboratory Details',
        description: 'Details of testing/analysis laboratory and location',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'authorization-documents',
        name: 'Authorization Documents',
        description: 'Authorization documents for test/analysis manufacturing activities',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'supporting-certificates',
        name: 'Supporting Certificates',
        description: 'Supporting certificates related to laboratory operations',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'undertaking-document',
        name: 'Undertaking/Declaration Document',
        description: 'Signed undertaking/declaration (if applicable)',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  // Blood Banking & Products (4 forms)
  {
    id: 'form-27c',
    code: '27C',
    title: 'Form 27C - Blood Bank Operation',
    subtitle: 'Hospital/Blood Bank',
    category: 'blood-banking',
    requiresInspection: true,
    estimatedTime: '60-80 minutes',
    fees: '₹50,000',
    documentRequirements: [
      {
        id: 'hospital-registration',
        name: 'Hospital/Institution Registration',
        description: 'Valid registration of the institution',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'blood-bank-license',
        name: 'Blood Bank License',
        description: 'State blood bank license',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'storage-facilities',
        name: 'Blood Storage Facilities',
        description: 'Details of storage equipment and conditions',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '15MB',
      },
      {
        id: 'pathologist-details',
        name: 'Pathologist Qualification',
        description: 'MD Pathology or equivalent qualification',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'testing-equipment',
        name: 'Testing Equipment Details',
        description: 'Blood testing and screening equipment',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-27e',
    code: '27E',
    title: 'Form 27E - Blood Products Manufacturing',
    subtitle: 'Blood Bank/Biologics Manufacturer',
    category: 'blood-banking',
    requiresInspection: true,
    estimatedTime: '80-100 minutes',
    fees: '₹80,000',
    documentRequirements: [
      {
        id: 'form-27c-license',
        name: 'Form 27C License',
        description: 'Valid blood bank operation license',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'manufacturing-facility',
        name: 'Manufacturing Facility Details',
        description: 'Specialized blood products manufacturing setup',
        mandatory: true,
        format: ['PDF'],
        maxSize: '20MB',
      },
      {
        id: 'quality-control',
        name: 'Quality Control Lab',
        description: 'In-house quality control laboratory',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'cold-chain',
        name: 'Cold Chain Management',
        description: 'Temperature controlled storage and transport',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  {
    id: 'form-27f',
    code: '27F',
    title: 'Form 27F - Blood Products (Cord Blood)',
    subtitle: 'Blood Bank/Cord Blood Bank',
    category: 'blood-banking',
    requiresInspection: true,
    estimatedTime: '70-90 minutes',
    fees: '₹60,000',
    documentRequirements: [
      {
        id: 'cord-blood-facility',
        name: 'Cord Blood Banking Facility',
        description: 'Specialized cord blood processing facility',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'cryopreservation',
        name: 'Cryopreservation Equipment',
        description: 'Liquid nitrogen storage and equipment',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '15MB',
      },
      {
        id: 'ethical-clearance',
        name: 'Ethical Committee Clearance',
        description: 'Ethics committee approval',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'stem-cell-expert',
        name: 'Stem Cell Expert Qualification',
        description: 'Qualification of stem cell specialist',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'blood-storage',
    code: 'BSC',
    title: 'Blood Storage Centre',
    subtitle: 'Hospital/Institution',
    category: 'blood-banking',
    requiresInspection: true,
    estimatedTime: '40-55 minutes',
    fees: '₹30,000',
    documentRequirements: [
      {
        id: 'institution-registration',
        name: 'Institution Registration',
        description: 'Hospital or institution registration',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'storage-equipment',
        name: 'Blood Storage Equipment',
        description: 'Blood bank refrigerators and monitoring',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '10MB',
      },
      {
        id: 'trained-staff',
        name: 'Trained Staff Details',
        description: 'Blood storage trained personnel',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'mou-blood-bank',
        name: 'MOU with Blood Bank',
        description: 'Agreement with licensed blood bank',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  // Cosmetics (2 forms)
  {
    id: 'form-31',
    code: '31',
    title: 'Form 31 - Cosmetics Manufacturing',
    subtitle: 'Cosmetics Manufacturer',
    category: 'cosmetics',
    requiresInspection: true,
    estimatedTime: '50-65 minutes',
    fees: '₹40,000',
    documentRequirements: [
      {
        id: 'premises-plan',
        name: 'Premises Plan/Layout',
        description: 'Layout plan of cosmetics manufacturing premises',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'supporting-certificates',
        name: 'Supporting Certificates',
        description: 'Technical and compliance certificates for cosmetics manufacturing',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'firm-registration',
        name: 'Firm Registration Documents',
        description: 'Firm/company registration and statutory documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'staff-qualification',
        name: 'Technical Staff Qualification Certificates',
        description: 'Qualification and experience proof for manufacturing/testing staff',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'ownership-tenancy-proof',
        name: 'Ownership/Tenancy Proof',
        description: 'Proof of ownership or tenancy of manufacturing premises',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  {
    id: 'form-31a',
    code: '31A',
    title: 'Form 31A - Loan Cosmetics Manufacturing',
    subtitle: 'Cosmetics Company/Brand Owner',
    category: 'cosmetics',
    requiresInspection: true,
    estimatedTime: '40-50 minutes',
    fees: '₹25,000',
    documentRequirements: [
      {
        id: 'letter-to-concern',
        name: 'Letter to Manufacturing Concern',
        description: 'Formal letter to the concern/manufacturer for loan licence arrangement',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
      {
        id: 'acceptance-letter',
        name: 'Acceptance/Consent Letter',
        description: 'Acceptance letter from manufacturing concern',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'labels-carton-specimens',
        name: 'Labels & Carton Specimens',
        description: 'Product labels and carton specimens for cosmetics',
        mandatory: true,
        format: ['PDF', 'JPG', 'PNG'],
        maxSize: '5MB',
      },
      {
        id: 'supporting-certificates',
        name: 'Supporting Certificates',
        description: 'Additional supporting certificates for loan licence evaluation',
        mandatory: true,
        format: ['PDF'],
        maxSize: '5MB',
      },
    ],
  },
  // Testing & Analysis (2 forms)
  {
    id: 'form-14a',
    code: '14A',
    title: 'Form 14A - Drug Test/Analysis Request',
    subtitle: 'Citizen/Purchaser',
    category: 'testing',
    requiresInspection: false,
    estimatedTime: '15-20 minutes',
    fees: '₹1,500',
    documentRequirements: [
      {
        id: 'drug-sample',
        name: 'Drug Sample Details',
        description: 'Complete details and photo of drug sample',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '5MB',
      },
      {
        id: 'purchase-receipt',
        name: 'Purchase Receipt',
        description: 'Receipt or proof of purchase',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '2MB',
      },
      {
        id: 'id-proof',
        name: 'Identity Proof',
        description: 'Aadhaar or any government ID',
        mandatory: true,
        format: ['PDF', 'JPG'],
        maxSize: '2MB',
      },
      {
        id: 'complaint-details',
        name: 'Complaint Details',
        description: 'Nature of complaint or concern',
        mandatory: true,
        format: ['PDF'],
        maxSize: '2MB',
      },
    ],
  },
  {
    id: 'form-36',
    code: '36',
    title: 'Form 36 - Lab Testing Approval',
    subtitle: 'Testing Laboratory',
    category: 'testing',
    requiresInspection: true,
    estimatedTime: '60-75 minutes',
    fees: '₹55,000',
    documentRequirements: [
      {
        id: 'testing-premises-layout',
        name: 'Testing Premises Layout',
        description: 'Layout plan of testing laboratory premises',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'supporting-certificates',
        name: 'Supporting Certificates',
        description: 'Laboratory certifications and compliance documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'expert-staff-certificates',
        name: 'Expert Staff Qualification Certificates',
        description: 'Qualification and experience certificates of expert staff and person-in-charge',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'testing-equipment-list',
        name: 'Testing Equipment List',
        description: 'Detailed list of laboratory testing equipment',
        mandatory: true,
        format: ['PDF', 'XLSX'],
        maxSize: '10MB',
      },
    ],
  },
  // New Drugs & Clinical Trials (1 form)
  {
    id: 'form-44',
    code: '44',
    title: 'Form 44 - New Drug Approval/Clinical Trials',
    subtitle: 'Pharma Manufacturer/Importer',
    category: 'new-drugs',
    requiresInspection: true,
    estimatedTime: '120-180 minutes',
    fees: '₹2,00,000',
    documentRequirements: [
      {
        id: 'chemical-pharma-data',
        name: 'Chemical & Pharmaceutical Data',
        description: 'Chemical and pharmaceutical data package',
        mandatory: true,
        format: ['PDF'],
        maxSize: '25MB',
      },
      {
        id: 'animal-toxicology-data',
        name: 'Animal Toxicology Data',
        description: 'Preclinical animal toxicology data and reports',
        mandatory: true,
        format: ['PDF'],
        maxSize: '25MB',
      },
      {
        id: 'clinical-trial-data',
        name: 'Clinical Trial Data',
        description: 'Clinical trial data and evidence package',
        mandatory: true,
        format: ['PDF'],
        maxSize: '30MB',
      },
      {
        id: 'bioavailability-stability-data',
        name: 'Bioavailability & Stability Data',
        description: 'Bioavailability, bioequivalence and stability reports',
        mandatory: true,
        format: ['PDF'],
        maxSize: '20MB',
      },
      {
        id: 'regulatory-status-data',
        name: 'Regulatory Status Information',
        description: 'Global regulatory approval/review status details',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
      {
        id: 'labels-monograph',
        name: 'Labels & Monograph',
        description: 'Proposed labels, package insert and monograph',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
    ],
  },
  // Medical Institution Recognition (1 form)
  {
    id: 'form-3f',
    code: '3F',
    title: 'Form 3F-3J - Medical Institution Recognition',
    subtitle: 'Medical Institution',
    category: 'medical-institution',
    requiresInspection: true,
    estimatedTime: '90-120 minutes',
    fees: '₹75,000',
    documentRequirements: [
      {
        id: 'institutional-documents',
        name: 'Institutional Documents',
        description: 'Core institutional and legal registration documents',
        mandatory: true,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'previous-certificate-withdrawal',
        name: 'Previous Certificate / Withdrawal Details',
        description: 'Previous recognition certificate or withdrawal details, if applicable',
        mandatory: false,
        format: ['PDF'],
        maxSize: '10MB',
      },
      {
        id: 'supporting-compliance-docs',
        name: 'Supporting Compliance Documents',
        description: 'Any additional compliance/supporting documents for department scrutiny',
        mandatory: true,
        format: ['PDF'],
        maxSize: '15MB',
      },
    ],
  },
];

// Helper function to get forms by category
export const getFormsByCategory = (categoryId: string): FormType[] => {
  return ALL_FORMS.filter((form) => form.category === categoryId);
};

// Helper function to get form by ID
export const getFormById = (formId: string): FormType | undefined => {
  return ALL_FORMS.find((form) => form.id === formId);
};

// Helper function to get form by code
export const getFormByCode = (code: string): FormType | undefined => {
  return ALL_FORMS.find((form) => form.code === code);
};
